/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sockets.server.core;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RetornoStatus implements org.apache.thrift.TEnum {
  OK(200),
  NO_CONTENT(204),
  NOT_FOUND(404),
  INTERNAL_ERROR(500);

  private final int value;

  private RetornoStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RetornoStatus findByValue(int value) { 
    switch (value) {
      case 200:
        return OK;
      case 204:
        return NO_CONTENT;
      case 404:
        return NOT_FOUND;
      case 500:
        return INTERNAL_ERROR;
      default:
        return null;
    }
  }
}
